//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFAAvalonia.Assets.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFAAvalonia.Assets.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于我们.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捕获模式:.
        /// </summary>
        public static string AdbCaptureMode {
            get {
                return ResourceManager.GetString("AdbCaptureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 额外参数.
        /// </summary>
        public static string AdbConfig {
            get {
                return ResourceManager.GetString("AdbConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb 编辑器.
        /// </summary>
        public static string AdbEditor {
            get {
                return ResourceManager.GetString("AdbEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdbInput (不推荐).
        /// </summary>
        public static string AdbInput {
            get {
                return ResourceManager.GetString("AdbInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触控模式:.
        /// </summary>
        public static string AdbInputMode {
            get {
                return ResourceManager.GetString("AdbInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb名称.
        /// </summary>
        public static string AdbName {
            get {
                return ResourceManager.GetString("AdbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb路径.
        /// </summary>
        public static string AdbPath {
            get {
                return ResourceManager.GetString("AdbPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adb地址.
        /// </summary>
        public static string AdbSerial {
            get {
                return ResourceManager.GetString("AdbSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加至上方.
        /// </summary>
        public static string AddAbove {
            get {
                return ResourceManager.GetString("AddAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加至下方.
        /// </summary>
        public static string AddBelow {
            get {
                return ResourceManager.GetString("AddBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string AddConfiguration {
            get {
                return ResourceManager.GetString("AddConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加任务.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高级设置.
        /// </summary>
        public static string AdvancedSetting {
            get {
                return ResourceManager.GetString("AdvancedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束后操作.
        /// </summary>
        public static string AfterTaskOption {
            get {
                return ResourceManager.GetString("AfterTaskOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有文件.
        /// </summary>
        public static string AllFilter {
            get {
                return ResourceManager.GetString("AllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接失败后尝试关闭并重启 ADB 进程.
        /// </summary>
        public static string AllowAdbHardRestart {
            get {
                return ResourceManager.GetString("AllowAdbHardRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接失败后尝试重启 ADB Server.
        /// </summary>
        public static string AllowAdbRestart {
            get {
                return ResourceManager.GetString("AllowAdbRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用/禁用背景动画，动画由当前活动效果驱动。.
        /// </summary>
        public static string AnimatedBackgroundDescription {
            get {
                return ResourceManager.GetString("AnimatedBackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动态背景动画.
        /// </summary>
        public static string AnimatedBackgroundTitle {
            get {
                return ResourceManager.GetString("AnimatedBackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要应用的控制器类型.
        /// </summary>
        public static string ApplyControllerType {
            get {
                return ResourceManager.GetString("ApplyControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在应用更新......
        /// </summary>
        public static string ApplyingUpdate {
            get {
                return ResourceManager.GetString("ApplyingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA 任务管理器.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoDetect (自动检测).
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动检测更新.
        /// </summary>
        public static string AutomaticDetectionUpdate {
            get {
                return ResourceManager.GetString("AutomaticDetectionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动 MFA 后直接隐藏.
        /// </summary>
        public static string AutomaticHide {
            get {
                return ResourceManager.GetString("AutomaticHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动 MFA 后直接最小化.
        /// </summary>
        public static string AutomaticMinimize {
            get {
                return ResourceManager.GetString("AutomaticMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动更新软件.
        /// </summary>
        public static string AutomaticUpdateMFA {
            get {
                return ResourceManager.GetString("AutomaticUpdateMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动更新资源.
        /// </summary>
        public static string AutomaticUpdateResource {
            get {
                return ResourceManager.GetString("AutomaticUpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动后操作.
        /// </summary>
        public static string AutoStartOption {
            get {
                return ResourceManager.GetString("AutoStartOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从内置背景样式中选择。.
        /// </summary>
        public static string BackgroundStyleDescription {
            get {
                return ResourceManager.GetString("BackgroundStyleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景样式.
        /// </summary>
        public static string BackgroundStyleTitle {
            get {
                return ResourceManager.GetString("BackgroundStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用/禁用背景过渡效果，切换效果时会有渐变过渡。.
        /// </summary>
        public static string BackgroundTransitionsDescription {
            get {
                return ResourceManager.GetString("BackgroundTransitionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景过渡效果.
        /// </summary>
        public static string BackgroundTransitionsTitle {
            get {
                return ResourceManager.GetString("BackgroundTransitionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本主题.
        /// </summary>
        public static string BaseTheme {
            get {
                return ResourceManager.GetString("BaseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蓝叠模拟器.
        /// </summary>
        public static string BlueStacks {
            get {
                return ResourceManager.GetString("BlueStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        public static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法启动任务.
        /// </summary>
        public static string CannotStart {
            get {
                return ResourceManager.GetString("CannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 捕获方式.
        /// </summary>
        public static string CaptureModeOption {
            get {
                return ResourceManager.GetString("CaptureModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查软件.
        /// </summary>
        public static string CheckMFA {
            get {
                return ResourceManager.GetString("CheckMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查资源.
        /// </summary>
        public static string CheckResource {
            get {
                return ResourceManager.GetString("CheckResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前剪贴板中数据不可转换为文本.
        /// </summary>
        public static string ClipboardDataError {
            get {
                return ResourceManager.GetString("ClipboardDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭软件.
        /// </summary>
        public static string CloseEmulator {
            get {
                return ResourceManager.GetString("CloseEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭MFA和软件.
        /// </summary>
        public static string CloseEmulatorAndMFA {
            get {
                return ResourceManager.GetString("CloseEmulatorAndMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启MFA和关闭软件.
        /// </summary>
        public static string CloseEmulatorAndRestartMFA {
            get {
                return ResourceManager.GetString("CloseEmulatorAndRestartMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭MFA.
        /// </summary>
        public static string CloseMFA {
            get {
                return ResourceManager.GetString("CloseMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取色器.
        /// </summary>
        public static string ColorPickerTitle {
            get {
                return ResourceManager.GetString("ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题.
        /// </summary>
        public static string ColorTheme {
            get {
                return ResourceManager.GetString("ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  常规设置 .
        /// </summary>
        public static string CommonSetting {
            get {
                return ResourceManager.GetString("CommonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置 &lt;{0}&gt; 添加成功！.
        /// </summary>
        public static string ConfigAddedSuccessfully {
            get {
                return ResourceManager.GetString("ConfigAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置名称 &lt;{0}&gt; 已存在！.
        /// </summary>
        public static string ConfigNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConfigNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件名不能为空！.
        /// </summary>
        public static string ConfigNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ConfigNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置名称.
        /// </summary>
        public static string ConfigurationName {
            get {
                return ResourceManager.GetString("ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出吗？.
        /// </summary>
        public static string ConfirmExitText {
            get {
                return ResourceManager.GetString("ConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA 正在运行任务.
        /// </summary>
        public static string ConfirmExitTitle {
            get {
                return ResourceManager.GetString("ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已连接.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接失败.
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接{0}时发生错误！.
        /// </summary>
        public static string ConnectingEmulatorOrWindow {
            get {
                return ResourceManager.GetString("ConnectingEmulatorOrWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在连接至{0}.......
        /// </summary>
        public static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接设置.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制器类型.
        /// </summary>
        public static string ControllerType {
            get {
                return ResourceManager.GetString("ControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已复制到剪切板.
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制错误信息.
        /// </summary>
        public static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制键.
        /// </summary>
        public static string CopyKey {
            get {
                return ResourceManager.GetString("CopyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制值.
        /// </summary>
        public static string CopyValue {
            get {
                return ResourceManager.GetString("CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前控制器.
        /// </summary>
        public static string CurrentController {
            get {
                return ResourceManager.GetString("CurrentController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该资源操作暂不支持 GitHub.
        /// </summary>
        public static string CurrentResourcesNotSupportGitHub {
            get {
                return ResourceManager.GetString("CurrentResourcesNotSupportGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该资源操作暂不支持 Mirror酱.
        /// </summary>
        public static string CurrentResourcesNotSupportMirror {
            get {
                return ResourceManager.GetString("CurrentResourcesNotSupportMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string DarkColor {
            get {
                return ResourceManager.GetString("DarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [调试模式].
        /// </summary>
        public static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试模式已开启。此模式会保存运行期间的截图、操作数据及图像识别可视化结果，可能会占用大量的存储空间！.
        /// </summary>
        public static string DebugModeWarning {
            get {
                return ResourceManager.GetString("DebugModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部不选.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钉钉.
        /// </summary>
        public static string DingTalk {
            get {
                return ResourceManager.GetString("DingTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钉钉群发送消息通知.
        /// </summary>
        public static string DingTalkMessageAsync {
            get {
                return ResourceManager.GetString("DingTalkMessageAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新版本下载失败.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载中......
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件中存在重复的任务名称:&quot;{0}&quot;！.
        /// </summary>
        public static string DuplicateTaskError {
            get {
                return ResourceManager.GetString("DuplicateTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表中已存在命名为&quot;{0}&quot;的任务.
        /// </summary>
        public static string DuplicateTaskNameError {
            get {
                return ResourceManager.GetString("DuplicateTaskNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性编辑器.
        /// </summary>
        public static string EditAttributeDialogTitle {
            get {
                return ResourceManager.GetString("EditAttributeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑控制器配置.
        /// </summary>
        public static string EditControllerConfiguration {
            get {
                return ResourceManager.GetString("EditControllerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑任务.
        /// </summary>
        public static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加属性.
        /// </summary>
        public static string EditTaskDialog_AddAttribute_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_AddAttribute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空属性.
        /// </summary>
        public static string EditTaskDialog_ClearAttribute_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ClearAttribute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空任务.
        /// </summary>
        public static string EditTaskDialog_ClearTask_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ClearTask_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取色.
        /// </summary>
        public static string EditTaskDialog_ColorExtraction_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_ColorExtraction_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务编辑器.
        /// </summary>
        public static string EditTaskDialog_Header {
            get {
                return ResourceManager.GetString("EditTaskDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Pipeline文件.
        /// </summary>
        public static string EditTaskDialog_Load_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Load_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件名称.
        /// </summary>
        public static string EditTaskDialog_PipelineFileName_Placeholder {
            get {
                return ResourceManager.GetString("EditTaskDialog_PipelineFileName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字识别.
        /// </summary>
        public static string EditTaskDialog_RecognitionText_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_RecognitionText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存Pipeline文件.
        /// </summary>
        public static string EditTaskDialog_SavePipeline_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_SavePipeline_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存任务名称.
        /// </summary>
        public static string EditTaskDialog_SaveTask_Button {
            get {
                return ResourceManager.GetString("EditTaskDialog_SaveTask_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 裁剪图片.
        /// </summary>
        public static string EditTaskDialog_Screenshot_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Screenshot_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择区域.
        /// </summary>
        public static string EditTaskDialog_SelectionRegion_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_SelectionRegion_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程图.
        /// </summary>
        public static string EditTaskDialog_ShowChart_Button {
            get {
                return ResourceManager.GetString("EditTaskDialog_ShowChart_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滑动.
        /// </summary>
        public static string EditTaskDialog_Swipe_Tooltip {
            get {
                return ResourceManager.GetString("EditTaskDialog_Swipe_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务名称:.
        /// </summary>
        public static string EditTaskDialog_TaskName_Title {
            get {
                return ResourceManager.GetString("EditTaskDialog_TaskName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务编辑器.
        /// </summary>
        public static string EditTaskDialog_Title {
            get {
                return ResourceManager.GetString("EditTaskDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑任务.
        /// </summary>
        public static string EditTaskTooltip {
            get {
                return ResourceManager.GetString("EditTaskTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟器.
        /// </summary>
        public static string Emulator {
            get {
                return ResourceManager.GetString("Emulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索模拟器!.
        /// </summary>
        public static string EmulatorDetectionStarted {
            get {
                return ResourceManager.GetString("EmulatorDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmulatorExtras (特化).
        /// </summary>
        public static string EmulatorExtras {
            get {
                return ResourceManager.GetString("EmulatorExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择模拟器:{0}.
        /// </summary>
        public static string EmulatorSelectionMessage {
            get {
                return ResourceManager.GetString("EmulatorSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用保存录像 (用于调试).
        /// </summary>
        public static string EnableRecording {
            get {
                return ResourceManager.GetString("EnableRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用保存截图 (用于调试).
        /// </summary>
        public static string EnableSaveDraw {
            get {
                return ResourceManager.GetString("EnableSaveDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入任务名称.
        /// </summary>
        public static string EnterTaskName {
            get {
                return ResourceManager.GetString("EnterTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详细信息.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建 GitHub issue.
        /// </summary>
        public static string ErrorFeedbackLinkText {
            get {
                return ResourceManager.GetString("ErrorFeedbackLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA 遇到了问题.
        /// </summary>
        public static string ErrorProlog {
            get {
                return ResourceManager.GetString("ErrorProlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可运行文件 (*.exe*)|*.exe*.
        /// </summary>
        public static string ExeFilter {
            get {
                return ResourceManager.GetString("ExeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机器人 Token.
        /// </summary>
        public static string ExternalNotificationBotToken {
            get {
                return ResourceManager.GetString("ExternalNotificationBotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钉钉 Secret.
        /// </summary>
        public static string ExternalNotificationDingTalkSecret {
            get {
                return ResourceManager.GetString("ExternalNotificationDingTalkSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 钉钉 Token.
        /// </summary>
        public static string ExternalNotificationDingTalkToken {
            get {
                return ResourceManager.GetString("ExternalNotificationDingTalkToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 频道 ID.
        /// </summary>
        public static string ExternalNotificationDiscordChannelId {
            get {
                return ResourceManager.GetString("ExternalNotificationDiscordChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户 ID.
        /// </summary>
        public static string ExternalNotificationDiscordUserId {
            get {
                return ResourceManager.GetString("ExternalNotificationDiscordUserId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用户 ID.
        /// </summary>
        public static string ExternalNotificationDiscordWebhookName {
            get {
                return ResourceManager.GetString("ExternalNotificationDiscordWebhookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱 账户.
        /// </summary>
        public static string ExternalNotificationEmailAccount {
            get {
                return ResourceManager.GetString("ExternalNotificationEmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱 Secret.
        /// </summary>
        public static string ExternalNotificationEmailSecret {
            get {
                return ResourceManager.GetString("ExternalNotificationEmailSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用的通知配置.
        /// </summary>
        public static string ExternalNotificationEnabled {
            get {
                return ResourceManager.GetString("ExternalNotificationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 飞书 ID.
        /// </summary>
        public static string ExternalNotificationLarkID {
            get {
                return ResourceManager.GetString("ExternalNotificationLarkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机器人 QQ.
        /// </summary>
        public static string ExternalNotificationQmsgBot {
            get {
                return ResourceManager.GetString("ExternalNotificationQmsgBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string ExternalNotificationQmsgKey {
            get {
                return ResourceManager.GetString("ExternalNotificationQmsgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ExternalNotificationQmsgServer {
            get {
                return ResourceManager.GetString("ExternalNotificationQmsgServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户 QQ.
        /// </summary>
        public static string ExternalNotificationQmsgUser {
            get {
                return ResourceManager.GetString("ExternalNotificationQmsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送测试.
        /// </summary>
        public static string ExternalNotificationSendTest {
            get {
                return ResourceManager.GetString("ExternalNotificationSendTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部通知.
        /// </summary>
        public static string ExternalNotificationSettings {
            get {
                return ResourceManager.GetString("ExternalNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要登录.
        /// </summary>
        public static string ExternalNotificationSmtpAuth {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发件人.
        /// </summary>
        public static string ExternalNotificationSmtpFrom {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string ExternalNotificationSmtpPassword {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口.
        /// </summary>
        public static string ExternalNotificationSmtpPort {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP 服务器.
        /// </summary>
        public static string ExternalNotificationSmtpServer {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 SSL.
        /// </summary>
        public static string ExternalNotificationSmtpSsl {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收件人.
        /// </summary>
        public static string ExternalNotificationSmtpTo {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string ExternalNotificationSmtpUser {
            get {
                return ResourceManager.GetString("ExternalNotificationSmtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聊天 ID.
        /// </summary>
        public static string ExternalNotificationTelegramChatId {
            get {
                return ResourceManager.GetString("ExternalNotificationTelegramChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请注意：外部通知功能目前仅会发送“所有任务完成”的通知。.
        /// </summary>
        public static string ExternalNotificationTips {
            get {
                return ResourceManager.GetString("ExternalNotificationTips", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Webhook URL.
        /// </summary>
        public static string ExternalNotificationWebhookUrl {
            get {
                return ResourceManager.GetString("ExternalNotificationWebhookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户 UID.
        /// </summary>
        public static string ExternalNotificationWxPusherUID {
            get {
                return ResourceManager.GetString("ExternalNotificationWxPusherUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取当前版本信息失败，无法更新。.
        /// </summary>
        public static string FailToGetCurrentVersionInfo {
            get {
                return ResourceManager.GetString("FailToGetCurrentVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法获取资源下载链接，更新失败。.
        /// </summary>
        public static string FailToGetDownloadUrl {
            get {
                return ResourceManager.GetString("FailToGetDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取最新版本信息失败.
        /// </summary>
        public static string FailToGetLatestVersionInfo {
            get {
                return ResourceManager.GetString("FailToGetLatestVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string FollowingSystem {
            get {
                return ResourceManager.GetString("FollowingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制定时启动.
        /// </summary>
        public static string ForceScheduledStart {
            get {
                return ResourceManager.GetString("ForceScheduledStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止当前任务，重启游戏并开始新任务.
        /// </summary>
        public static string ForceScheduledStartTip {
            get {
                return ResourceManager.GetString("ForceScheduledStartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏资源已更新，请重启软件。.
        /// </summary>
        public static string GameResourceUpdated {
            get {
                return ResourceManager.GetString("GameResourceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用模式.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在获取最新框架......
        /// </summary>
        public static string GettingLatestMaaFW {
            get {
                return ResourceManager.GetString("GettingLatestMaaFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在获取最新资源......
        /// </summary>
        public static string GettingLatestResources {
            get {
                return ResourceManager.GetString("GettingLatestResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在获取最新软件......
        /// </summary>
        public static string GettingLatestSoftware {
            get {
                return ResourceManager.GetString("GettingLatestSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源码: GitHub.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此选项页为全局配置.
        /// </summary>
        public static string GlobalConfigTip {
            get {
                return ResourceManager.GetString("GlobalConfigTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string GpuOptionAuto {
            get {
                return ResourceManager.GetString("GpuOptionAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不使用.
        /// </summary>
        public static string GpuOptionDisable {
            get {
                return ResourceManager.GetString("GpuOptionDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在尝试关闭并重启 ADB 进程.
        /// </summary>
        public static string HardRestartAdb {
            get {
                return ResourceManager.GetString("HardRestartAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 键入 退格/Esc/Delete 清除当前热键.
        /// </summary>
        public static string HotKeyChangingTip {
            get {
                return ResourceManager.GetString("HotKeyChangingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [热键] 开始/停止任务.
        /// </summary>
        public static string HotKeyLinkStart {
            get {
                return ResourceManager.GetString("HotKeyLinkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未设置.
        /// </summary>
        public static string HotKeyNotSet {
            get {
                return ResourceManager.GetString("HotKeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ 该热键已被占用.
        /// </summary>
        public static string HotKeyOccupiedWarning {
            get {
                return ResourceManager.GetString("HotKeyOccupiedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按下任意组合键....
        /// </summary>
        public static string HotKeyPressing {
            get {
                return ResourceManager.GetString("HotKeyPressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 热键设置.
        /// </summary>
        public static string HotKeySettings {
            get {
                return ResourceManager.GetString("HotKeySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [热键] 显示/隐藏软件.
        /// </summary>
        public static string HotKeyShowGui {
            get {
                return ResourceManager.GetString("HotKeyShowGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片浏览器.
        /// </summary>
        public static string ImageBrowserTitle {
            get {
                return ResourceManager.GetString("ImageBrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片文件 (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp.
        /// </summary>
        public static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化控制器时发生错误！.
        /// </summary>
        public static string InitControllerFailed {
            get {
                return ResourceManager.GetString("InitControllerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化控制器成功.
        /// </summary>
        public static string InitControllerSuccess {
            get {
                return ResourceManager.GetString("InitControllerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化MAA实例失败，发生连接错误或资源文件损坏，请参阅日志..
        /// </summary>
        public static string InitInstanceFailed {
            get {
                return ResourceManager.GetString("InitInstanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入资源成功.
        /// </summary>
        public static string InitResourcesSuccess {
            get {
                return ResourceManager.GetString("InitResourcesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触控模式.
        /// </summary>
        public static string InputModeOption {
            get {
                return ResourceManager.GetString("InputModeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题反馈.
        /// </summary>
        public static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON 文件 (*.json)|*.json|所有文件 (*.*)|*.*.
        /// </summary>
        public static string JSONFilter {
            get {
                return ResourceManager.GetString("JSONFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性类型:.
        /// </summary>
        public static string LabelPropertyType {
            get {
                return ResourceManager.GetString("LabelPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言(Language).
        /// </summary>
        public static string LanguageOption {
            get {
                return ResourceManager.GetString("LanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择应用程序的显示语言，更改将立即生效。.
        /// </summary>
        public static string LanguageOptionDescription {
            get {
                return ResourceManager.GetString("LanguageOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言设置.
        /// </summary>
        public static string LanguageSettings {
            get {
                return ResourceManager.GetString("LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 飞书.
        /// </summary>
        public static string Lark {
            get {
                return ResourceManager.GetString("Lark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷电模拟器.
        /// </summary>
        public static string LDPlayer {
            get {
                return ResourceManager.GetString("LDPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string LightColor {
            get {
                return ResourceManager.GetString("LightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 任意 文件.
        /// </summary>
        public static string LoadFileTitle {
            get {
                return ResourceManager.GetString("LoadFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择图片文件.
        /// </summary>
        public static string LoadImageTitle {
            get {
                return ResourceManager.GetString("LoadImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在初始化控制器.
        /// </summary>
        public static string LoadingController {
            get {
                return ResourceManager.GetString("LoadingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在载入资源.
        /// </summary>
        public static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件加载或解析失败: {0}.
        /// </summary>
        public static string LoadPipelineErrorMessage {
            get {
                return ResourceManager.GetString("LoadPipelineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择 Pipeline 文件.
        /// </summary>
        public static string LoadPipelineTitle {
            get {
                return ResourceManager.GetString("LoadPipelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源加载失败！.
        /// </summary>
        public static string LoadResourcesFailed {
            get {
                return ResourceManager.GetString("LoadResourcesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        public static string LogRecord {
            get {
                return ResourceManager.GetString("LogRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框架已为最新版本！.
        /// </summary>
        public static string MaaFwIsLatestVersion {
            get {
                return ResourceManager.GetString("MaaFwIsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框架版本.
        /// </summary>
        public static string MaaFWVersion {
            get {
                return ResourceManager.GetString("MaaFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaaTouch (实验功能).
        /// </summary>
        public static string MaaTouch {
            get {
                return ResourceManager.GetString("MaaTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件已为最新版本！.
        /// </summary>
        public static string MFAIsLatestVersion {
            get {
                return ResourceManager.GetString("MFAIsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小化时隐藏至托盘.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniTouch (默认).
        /// </summary>
        public static string MiniTouch {
            get {
                return ResourceManager.GetString("MiniTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请购买 Mirror 酱服务以实现自动更新，或将下载源切换至 GitHub.
        /// </summary>
        public static string MirrorAutoUpdatePrompt {
            get {
                return ResourceManager.GetString("MirrorAutoUpdatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror 酱.
        /// </summary>
        public static string MirrorChyan {
            get {
                return ResourceManager.GetString("MirrorChyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror 酱的使用已达到上限.
        /// </summary>
        public static string MirrorUseLimitReached {
            get {
                return ResourceManager.GetString("MirrorUseLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MuMu模拟器12.
        /// </summary>
        public static string MuMuEmulator12 {
            get {
                return ResourceManager.GetString("MuMuEmulator12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有新版本可用！最新版本:.
        /// </summary>
        public static string NewVersionAvailableLatestVersion {
            get {
                return ResourceManager.GetString("NewVersionAvailableLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新版本下载完成.
        /// </summary>
        public static string NewVersionDownloadCompletedTitle {
            get {
                return ResourceManager.GetString("NewVersionDownloadCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在后台下载…….
        /// </summary>
        public static string NewVersionFoundDescDownloading {
            get {
                return ResourceManager.GetString("NewVersionFoundDescDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到模拟器!.
        /// </summary>
        public static string NoEmulatorFound {
            get {
                return ResourceManager.GetString("NoEmulatorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前没有可结束的任务!.
        /// </summary>
        public static string NoTaskToStop {
            get {
                return ResourceManager.GetString("NoTaskToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到窗口!.
        /// </summary>
        public static string NoWindowFound {
            get {
                return ResourceManager.GetString("NoWindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜神模拟器.
        /// </summary>
        public static string Nox {
            get {
                return ResourceManager.GetString("Nox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 好的.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择要操作的控制器.
        /// </summary>
        public static string OperateController {
            get {
                return ResourceManager.GetString("OperateController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴到上方.
        /// </summary>
        public static string PasteAbove {
            get {
                return ResourceManager.GetString("PasteAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴到下方.
        /// </summary>
        public static string PasteBelow {
            get {
                return ResourceManager.GetString("PasteBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性能设置.
        /// </summary>
        public static string PerformanceSettings {
            get {
                return ResourceManager.GetString("PerformanceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入Pipeline文件时出现错误: {0}.
        /// </summary>
        public static string PipelineLoadError {
            get {
                return ResourceManager.GetString("PipelineLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束后脚本.
        /// </summary>
        public static string Post_script {
            get {
                return ResourceManager.GetString("Post-script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始前脚本.
        /// </summary>
        public static string Prescript {
            get {
                return ResourceManager.GetString("Prescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目链接: .
        /// </summary>
        public static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买链接.
        /// </summary>
        public static string PurchaseLink {
            get {
                return ResourceManager.GetString("PurchaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域选择器.
        /// </summary>
        public static string RegionSelectorTitle {
            get {
                return ResourceManager.GetString("RegionSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册自定义Action:{0}.
        /// </summary>
        public static string RegisterCustomAction {
            get {
                return ResourceManager.GetString("RegisterCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册自定义Recognizer:{0}.
        /// </summary>
        public static string RegisterCustomRecognizer {
            get {
                return ResourceManager.GetString("RegisterCustomRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在注册自定义行动.
        /// </summary>
        public static string RegisteringCustomAction {
            get {
                return ResourceManager.GetString("RegisteringCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在注册自定义识别器.
        /// </summary>
        public static string RegisteringCustomRecognizer {
            get {
                return ResourceManager.GetString("RegisteringCustomRecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住连接.
        /// </summary>
        public static string RememberAdb {
            get {
                return ResourceManager.GetString("RememberAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复次数.
        /// </summary>
        public static string RepeatOption {
            get {
                return ResourceManager.GetString("RepeatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新扫描控制器.
        /// </summary>
        public static string RescanController {
            get {
                return ResourceManager.GetString("RescanController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源下载源.
        /// </summary>
        public static string ResourceDownloadSource {
            get {
                return ResourceManager.GetString("ResourceDownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源链接: .
        /// </summary>
        public static string ResourceLink {
            get {
                return ResourceManager.GetString("ResourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源名称.
        /// </summary>
        public static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源类型.
        /// </summary>
        public static string ResourceOption {
            get {
                return ResourceManager.GetString("ResourceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源已为最新版本！.
        /// </summary>
        public static string ResourcesAreLatestVersion {
            get {
                return ResourceManager.GetString("ResourcesAreLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源版本.
        /// </summary>
        public static string ResourceVersion {
            get {
                return ResourceManager.GetString("ResourceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新启动.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在尝试重启 ADB Server.
        /// </summary>
        public static string RestartAdb {
            get {
                return ResourceManager.GetString("RestartAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启MFA.
        /// </summary>
        public static string RestartMFA {
            get {
                return ResourceManager.GetString("RestartMFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启电脑.
        /// </summary>
        public static string RestartPC {
            get {
                return ResourceManager.GetString("RestartPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADB 连接失败时尝试启动模拟器.
        /// </summary>
        public static string RetryOnDisconnected {
            get {
                return ResourceManager.GetString("RetryOnDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行设置.
        /// </summary>
        public static string RunningSettings {
            get {
                return ResourceManager.GetString("RunningSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存任务失败!.
        /// </summary>
        public static string SaveFailureMessage {
            get {
                return ResourceManager.GetString("SaveFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功！.
        /// </summary>
        public static string SavePipelineSuccess {
            get {
                return ResourceManager.GetString("SavePipelineSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表中存在相同命名的任务!.
        /// </summary>
        public static string SavePipelineWarning {
            get {
                return ResourceManager.GetString("SavePipelineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存任务成功!.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时执行.
        /// </summary>
        public static string ScheduleSettings {
            get {
                return ResourceManager.GetString("ScheduleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截图耗时: {0}ms({1}).
        /// </summary>
        public static string ScreencapCost {
            get {
                return ResourceManager.GetString("ScreencapCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截图用时过长: {0}ms({1}).
        /// </summary>
        public static string ScreencapErrorTip {
            get {
                return ResourceManager.GetString("ScreencapErrorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 截图用时较长: {0}ms({1}).
        /// </summary>
        public static string ScreencapWarningTip {
            get {
                return ResourceManager.GetString("ScreencapWarningTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择可运行文件.
        /// </summary>
        public static string SelectExecutableFile {
            get {
                return ResourceManager.GetString("SelectExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一张已有图片.
        /// </summary>
        public static string SelectExistingImage {
            get {
                return ResourceManager.GetString("SelectExistingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下次不再提示.
        /// </summary>
        public static string ShowDisclaimerNoMore {
            get {
                return ResourceManager.GetString("ShowDisclaimerNoMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示节点命中弹窗 (用于调试).
        /// </summary>
        public static string ShowHitDraw {
            get {
                return ResourceManager.GetString("ShowHitDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关机.
        /// </summary>
        public static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 滑动获取器.
        /// </summary>
        public static string SliderControlTitle {
            get {
                return ResourceManager.GetString("SliderControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件路径.
        /// </summary>
        public static string SoftwarePath {
            get {
                return ResourceManager.GetString("SoftwarePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件更新.
        /// </summary>
        public static string SoftwareUpdate {
            get {
                return ResourceManager.GetString("SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件版本.
        /// </summary>
        public static string SoftwareVersion {
            get {
                return ResourceManager.GetString("SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始任务.
        /// </summary>
        public static string StartTask {
            get {
                return ResourceManager.GetString("StartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附加命令.
        /// </summary>
        public static string StartupParameter {
            get {
                return ResourceManager.GetString("StartupParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动脚本.
        /// </summary>
        public static string StartupScript {
            get {
                return ResourceManager.GetString("StartupScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动设置.
        /// </summary>
        public static string StartupSettings {
            get {
                return ResourceManager.GetString("StartupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动软件.
        /// </summary>
        public static string StartupSoftware {
            get {
                return ResourceManager.GetString("StartupSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动软件并启动脚本.
        /// </summary>
        public static string StartupSoftwareAndScript {
            get {
                return ResourceManager.GetString("StartupSoftwareAndScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在停止.......
        /// </summary>
        public static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止任务失败.
        /// </summary>
        public static string StoppingFailed {
            get {
                return ResourceManager.GetString("StoppingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止任务.
        /// </summary>
        public static string StopTask {
            get {
                return ResourceManager.GetString("StopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换配置.
        /// </summary>
        public static string SwitchConfiguration {
            get {
                return ResourceManager.GetString("SwitchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换语言 🌐.
        /// </summary>
        public static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟器.
        /// </summary>
        public static string TabADB {
            get {
                return ResourceManager.GetString("TabADB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桌面应用.
        /// </summary>
        public static string TabWin32 {
            get {
                return ResourceManager.GetString("TabWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已放弃本次任务.
        /// </summary>
        public static string TaskAbandoned {
            get {
                return ResourceManager.GetString("TaskAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已全部完成！.
        /// </summary>
        public static string TaskAllCompleted {
            get {
                return ResourceManager.GetString("TaskAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已全部完成！\n(用时 {0}h {1}m {2}s).
        /// </summary>
        public static string TaskAllCompletedWithTime {
            get {
                return ResourceManager.GetString("TaskAllCompletedWithTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已完成.
        /// </summary>
        public static string TaskCompleted {
            get {
                return ResourceManager.GetString("TaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务说明.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务列表.
        /// </summary>
        public static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline文件中任务的{0}使用了不存在的任务:&quot;{1}&quot;！.
        /// </summary>
        public static string TaskNotFoundError {
            get {
                return ResourceManager.GetString("TaskNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务设置.
        /// </summary>
        public static string TaskSettings {
            get {
                return ResourceManager.GetString("TaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别{0}时发生错误: {1}.
        /// </summary>
        public static string TaskStackError {
            get {
                return ResourceManager.GetString("TaskStackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始任务: {0}.
        /// </summary>
        public static string TaskStart {
            get {
                return ResourceManager.GetString("TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务已中止.
        /// </summary>
        public static string TaskStopped {
            get {
                return ResourceManager.GetString("TaskStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字识别器.
        /// </summary>
        public static string TextRecognizerTitle {
            get {
                return ResourceManager.GetString("TextRecognizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 界面主题.
        /// </summary>
        public static string ThemeOption {
            get {
                return ResourceManager.GetString("ThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题设置.
        /// </summary>
        public static string ThemeSettings {
            get {
                return ResourceManager.GetString("ThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时.
        /// </summary>
        public static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义配置选择.
        /// </summary>
        public static string TimerCustomConfig {
            get {
                return ResourceManager.GetString("TimerCustomConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将提前两分钟重启并切换配置.
        /// </summary>
        public static string TimerCustomConfigTip {
            get {
                return ResourceManager.GetString("TimerCustomConfigTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签顺序可拖动.
        /// </summary>
        public static string TooltipDragLabel {
            get {
                return ResourceManager.GetString("TooltipDragLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string TooltipRefresh {
            get {
                return ResourceManager.GetString("TooltipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在尝试重连.
        /// </summary>
        public static string TryToReconnectByAdb {
            get {
                return ResourceManager.GetString("TryToReconnectByAdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在尝试启动模拟器.
        /// </summary>
        public static string TryToStartEmulator {
            get {
                return ResourceManager.GetString("TryToStartEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 界面设置.
        /// </summary>
        public static string UiSettings {
            get {
                return ResourceManager.GetString("UiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未连接.
        /// </summary>
        public static string Unconnected {
            get {
                return ResourceManager.GetString("Unconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新完成.
        /// </summary>
        public static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框架更新.
        /// </summary>
        public static string UpdateMaaFW {
            get {
                return ResourceManager.GetString("UpdateMaaFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源更新.
        /// </summary>
        public static string UpdateResource {
            get {
                return ResourceManager.GetString("UpdateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新设置.
        /// </summary>
        public static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 GPU 加速推理.
        /// </summary>
        public static string UseGpuForInference {
            get {
                return ResourceManager.GetString("UseGpuForInference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待软件启动时间(秒).
        /// </summary>
        public static string WaitSoftware {
            get {
                return ResourceManager.GetString("WaitSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待{0}启动时间(秒): {1}(s).
        /// </summary>
        public static string WaitSoftwareTime {
            get {
                return ResourceManager.GetString("WaitSoftwareTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法连接至{0}.
        /// </summary>
        public static string Warning_CannotConnect {
            get {
                return ResourceManager.GetString("Warning_CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索窗口!.
        /// </summary>
        public static string WindowDetectionStarted {
            get {
                return ResourceManager.GetString("WindowDetectionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择窗口:{0}.
        /// </summary>
        public static string WindowSelectionMessage {
            get {
                return ResourceManager.GetString("WindowSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务流程图.
        /// </summary>
        public static string WorkflowDiagramTitle {
            get {
                return ResourceManager.GetString("WorkflowDiagramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微信公众号.
        /// </summary>
        public static string WxPusher {
            get {
                return ResourceManager.GetString("WxPusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
